services:
  coredns:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./build/Corefile:/app/Corefile
      - ./build/examples:/app/examples