name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm, arm64]
        exclude:
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.22'

      - name: Get CoreDNS
        run: |
          git clone https://github.com/coredns/coredns.git
          cd coredns
          echo "rpz:github.com/${{ github.repository }}" >> plugin.cfg

      - name: Build
        run: |
          cd coredns
          go get github.com/mwantia/coredns-rpz-plugin
          go generate
          OUTPUT="coredns"
          if [ "${{ matrix.goos }}" = "windows"]; then
            OUTPUT+='.exe'
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $OUTPUT
        env:
          CGO_ENABLED: 0

      - name: Create Archive
        run: |
          cd coredns
          INPUT="coredns"
          if [ "${{ matrix.goos }}" = "windows"]; then
            INPUT+='.exe'
          fi
          zip coredns-rpz-${{ matrix.goos }}-${{ matrix.goarch }}.zip $INPUT

      - name: Upload release Archive
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: coredns/coredns-rpz-${{ matrix.goos }}-${{ matrix.goarch }}.*
          file_glob: true